export const data = {
  products: [
    {
      name: "First Shirt",
      slug: "first-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      reviews: 8,
      inStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Second Shirt",
      slug: "second-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 80,
      brand: "Adidas",
      rating: 3.2,
      reviews: 10,
      inStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Third Shirt",
      slug: "third-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 90,
      brand: "Raymond",
      rating: 4.5,
      reviews: 3,
      inStock: 20,
      description: "A popular shirt",
    },
    {
      name: "First Pants",
      slug: "first-pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 90,
      brand: "Oliver",
      rating: 2.9,
      reviews: 13,
      inStock: 20,
      description: "Smart looking pants",
    },
    {
      name: "Second Pants",
      slug: "second-pants",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 95,
      brand: "Zara",
      rating: 3.5,
      reviews: 7,
      inStock: 20,
      description: "very popular pants",
    },
    {
      name: "Third Pants",
      slug: "third-pants",
      category: "Pants",
      image: "/images/pants3.jpg",
      price: 75,
      brand: "Casely",
      rating: 2.4,
      reviews: 14,
      inStock: 20,
      description: "Casual pants",
    },
  ],
};
